spring:
  application:
    name: test-app
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mariadb://localhost:3306/testapp
    username: ck
    password: "0527"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: admin
  # 웹 리소스 관련 설정 추가
  web:
    resources:
      cache:
        period: 604800
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    max-connections: 10000
    accept-count: 100
    connection-timeout: 20000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml,image/jpeg,image/png,image/gif
    min-response-size: 2048

logging:
  level:
    root: INFO
    com.jacob.testapp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/test-app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30 
