server:
  port: 8081
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/user_service_db
    username: root
    password: password
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      minimum-idle: 5

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.jacob.userservice.model

logging:
  level:
    root: INFO
    com.jacob.userservice: DEBUG
    org.mybatis: DEBUG
    com.jacob.userservice.repository: DEBUG

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:secret-key-for-user-service-development-environment-only}
    token-validity-in-seconds: 86400

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 