server:
  port: 8083
  servlet:
    context-path: /order-service

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/order_service_db
    username: root
    password: password
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      minimum-idle: 5
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=300s

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.jacob.orderservice.model

logging:
  level:
    root: INFO
    com.jacob.orderservice: DEBUG
    org.mybatis: DEBUG
    com.jacob.orderservice.repository: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# 외부 서비스 호출 설정
external-services:
  user-service:
    url: http://localhost:8081/user-service/api
  product-service:
    url: http://localhost:8082/product-service/api 