server:
  port: 8082
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/product_service_db
    username: root
    password: password
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      minimum-idle: 5
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=300s

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.jacob.productservice.model

logging:
  level:
    root: INFO
    com.jacob.productservice: DEBUG
    org.mybatis: DEBUG
    com.jacob.productservice.repository: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# 사용자 서비스 호출 설정 (필요 시)
external-services:
  user-service-url: http://localhost:8081/user-service/api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# MinIO 설정 추가
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: book-image 